name: Compile exes with makefile

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Install dependencies
      run: |
        cd ..
        git clone https://github.com/benRenard/miniDMSL.git miniDMSL 
           
    #- name: Install dependencies
    #  run: |
    #    cd makefile
    #    make
