name: Build on Windows

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
 
    - name: Install dependencies
      run: |
        cd ..
        git clone https://github.com/benRenard/miniDMSL.git miniDMSL 
        git clone https://github.com/benRenard/BMSL.git BMSL 
        
    - name: Call make
      run: |
        cd makefile
        make
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: BaM executable
        path: makefile/BaM.exe
        
    - name: Test executable
      run: |
        cd makefile
        ./BaM.exe --version
        ./BaM.exe
